[package]
name = "prototype3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "square"
path = "src/main.rs"

[dependencies]
rand = "0.7.3"
wasm-bindgen = "=0.2.61"